import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Counter, Header, Footer } from '@components';

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Counter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Counter />
      <Footer />
    </div>
  );
}
